//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task3_mvc_ss.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {

        [Required]
        public int id { get; set; }
        [Required(ErrorMessage ="*")]

        [StringLength(12)]
        [Display(Name = "First Name")]

        public string First_Name { get; set; }
        [Required]
        [StringLength(12)]
        [Display]
        public string Last_name { get; set; }
        [EmailAddress]
        [Required]
        [Display(Name = "Email")]
        public string E_mail { get; set; }
        [RegularExpression("((079)|(078)|(077)){1}[0-9]{7}", ErrorMessage = "Number must be Joirdanian")]
        public string Phone { get; set; }
        [Range(18,50)]
        public Nullable<int> Age { get; set; }
        [MaxLength(10)]
        [Required]
        [Display(Name = "JobTitle ")]
        public string Job_Title { get; set; }
        [Required]
        public string imge { get; set; }
        [Required]
        public string CV { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string GenderDisplay
        {
            get
            {
                if (Gender == null)
                {
                    return "Not specified";
                }
                else
                {
                    return Gender == true ? "Male" : "Female";
                }
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
