//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task3_mvc_ss.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
      

        public int id { get; set; }
        [Required(ErrorMessage = "*")]

        [StringLength(12)]
        [Display(Name = "FirstName")]

        public string First_Name { get; set; }
        [Required(ErrorMessage = "*")]
        [StringLength(12)]
        [Display(Name = "LastName ")]
        public string Last_name { get; set; }
        [EmailAddress]
        [Required(ErrorMessage = "*")]
        [Display(Name = "Email")]
        public string E_mail { get; set; }
        //[RegularExpression(@"^(?[0]{1}?[7]{1}?([7-9]{1}))?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Entered phone format is not valid.")]
        public string Phone { get; set; }
        [Range(18,50)]
        public Nullable<int> Age { get; set; }
        [MaxLength(10)]
        [Required(ErrorMessage = "*")]
        [Display(Name = "JobTitle ")]
        public string Job_Title { get; set; }
        public Nullable<bool> Gender { get; set; }
    }
}
