//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_2023
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public decimal EmployeePhone { get; set; }
        public string EmployeeEmail { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public string Roles { get; set; }
        public string Gender { get; set; }
    }
}
