//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taskMvc_2_1_2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public Nullable<bool> isDeliverd { get; set; }
        public int user_id { get; set; }
        public Nullable<int> qty { get; set; }
    
        public virtual product product { get; set; }
    }
}
